### ISSUE TITLE
Blood DK WA Green Icons with Artifact Equipped

### ISSUE THREAD

**Issue by NKDi** [rnyberg/Redfella-s-WA-Custom-Functions#2]
When used with the Maw of the Damned equipped, The "Rotation" WA starts showing solid green icons and prevents opening of the Blizzard artifact weapon frame. No visible errors are thrown to help track this down. Reloading the UI allows use of the artifact window for a short time but the green icon issue does not resolve even temporarily.

WA version 2.2.1.3
Rotation WA from Aug 28th.

**Comment by rnyberg** [comment]
Do you have LibArtifactData installed as I've instructed over at https://docs.google.com/document/d/1EwNIq_jWJodPhqOxd1H6LGzk8lMGDk-MaSMCaGscYWE/edit

?

**Comment by rnyberg** [comment]
Seems to be working properly with Maw of the Damned equipped: https://www.dropbox.com/s/irlpe22fpfg2gnn/2016-08-31_13-43-26.mp4?dl=0

Make sure you have the latest WeakAuras2 installed since the version before that had a bug in importing that broke down custom functions (leading to green icons). Re-import and report back if you still have problems.

**Comment by NKDi** [comment]
Yeah I have LibArtifactData installed. The version from Aug 14th. I'll see if I can dig into this more and try to figure out what's causing it and why you cannot reproduce it.
